---
- name: Install Fontconfig and OpenJDK 17
  ansible.builtin.apt:
    name:
      - fontconfig
      - openjdk-17-jre
    state: present

- name: Remove existing Jenkins GPG key (if exists)
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: absent

- name: Remove existing Jenkins repository (if exists)
  ansible.builtin.apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: absent

- name: Add Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] http://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Start Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins service
  service:
    name: jenkins
    state: restarted
